POST http://localhost:2000/books/add
Content-Type: application/json

{
    "book_title": "malaika",
    "book_author" : "hiii",
    "book_desc" : "Start",
    "book_genre" : "Start"
    
}

###

GET http://localhost:2000/books


###
PUT  http://localhost:2000/books/update/601bb65544921b42d402cefb
Content-Type: application/json

{
    "book_title": "osama",
    "book_author" : "hiii",
    "book_desc" : "Start",
    "book_genre" : "Start"
    
}
